# Generated by Django 4.1.6 on 2023-02-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Pessoas',
        ),
    ]
