# Generated by Django 4.1.6 on 2023-02-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_rename_usuarios_pessoas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
    ]
